libreiser4 libraries link against libmisc too
Statically link libmisc in libreiser4 libraries.  Being a convenience
library, libmisc is not installed; libreiser4 will not resolve misc_*
functions unless there is a shared library providing them or they are
statically linked.  Solves 'undefined reference to misc_str2long' and
alike when linking against the installed libreiser4 library.

Note that libaux is statically linked in libmisc, so if you need both
just link to libmisc in order to prevent redefinition of symbols.  If
you only need libaux, then link to the former.

Being libmisc now part of libreiser4, linking to the latter will make
misc_* functions available as shared symbols via libreiser4.  Linking
to libmisc (before libreiser4) will make them statically available.

The old behavior of statically linking misc_* functions by demo/* and
progs/* is preserved. libmisc is now statically linked in libreiser4,
demo, and progs.

As a side note, c9e2f5cc3be55434ea0d508d42112ff951fcce91 removed cpfs
and resizefs as SUBDIRS from progs/Makefile.am, hence they are unused
during compilation/installation. They are patched anyway just to keep
an eye on what is happening in progs/*.